travis:
  secure:
    BINSTAR_TOKEN: h9N/hkjSvmaPkwrgiLJAbFTsP+VjFmwiJwBiDITI0Gug0TL6TYxL/K517z/+DD3/w3DTszjT4x246nM4jHHm5eLwudRfDuHvonI2Bk+G7EdzjH5Y8zg/gdS4HH41WP+k+J0ETGLJ4Uff/AVE83Uu1reqyRONKit++rnMlnM24cNPGySHjSmLi5gzVcfp9QF8gpBPwhOxtbcL0zeEnBeKDn6NIwavssbPTTDsGRJIzJOMnyItR+4AhbJsSNu/xJS2pVuwlo7bBgYiNS4/Fvh/FWF3l89r62io4Hhu8WVuYsPQf2KarkWS3ZQLHlXTP0dx3anHdfnT2/1CF1ZSjL/m++LeKZAlG6G0mb2HEcjc8VS6Llfsn8JbdJVC9blQBTg2VvES/XjAqyeuMySNAd3i6n4WQlipPiTiTwbRwEIyQId1gD3qXmhfBF/1fSfQnd+s8zA/RgyDZe3erBW9K5PkTHHlWVL/B3ijnT6FIR9QBJk0nDlimY1wJ0hDRJC//PHS4nhVj/2DNUNu12O2Le7gyBheVmVfz2CsS+JtqX8E4NHLkr8bA8khAFNxiJTkJpiD4q/QOwa73rhumOTtv1ZDb5ZBduNCClt3i36Q+cc4ST18p7SqgckUhZp9+/+Z0ACzVnl0VbV1aiRCvT8NS5l33Fv658XPRR2V0WgQc8YasOs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
