travis:
  secure:
    BINSTAR_TOKEN: Atp8X1uGI5tpPzbblYQaLZc6Vvqttr/mSfTM29isAMz0PODE2W6RLRgL0pehhMWac9npecXlZ2MBJ8Ah0lOOpGVBMu8USB5wNEAbrjMU4huazFxh2mAiwvS7hBqRQ/PnzKuh2YOzMTkF9AOZOJeIFhnZ4CtP4xWeeTTSPMpldofOu2Q4BXa9MsUM0QtiEXxc1+kH46Jrk2yJBvQBBs5Nf2HNVJud5b0xwhGIPqpAEgrUXx98+DgsgZv7XQr4ag8P1MGU/sIiL5BErrlLMPUTT9B2tPu/spiQ3n0F1cImU7ccFEcHt5OEOXi1d6jLT4ueFCe/TpBGTf2OcBqk3WTMkTvw1z86O3zc2oNYjzZkJ6QVPadYeohVsLx5rboTKWd+ZP7+e1XYVfk8MLtqGM1VyN6sMFXGECZFi39NcW2pz2UyX2Sne/QocBbAp9kcnagOnm4W//I9BNbB7oPxcspENTeQmp+zDIDB7Vx8L5IkOqj8K+WbwwXfPeu/rSXJnx4rUx+9UB0su9n/OG0J+rnzj95aCpeoYEUIDeLX37ZJFPe7RAbZJO+Tj24fV1RMQMUT1fpMu4nQAghO/NgFTmrQVFHbdrBDpW8FVwynFNMO89Sw6OnqDsPY2CDroQ99IzAywq5Jr6NDe/kTuTyt106rIBRwMnVt8AxGXQV2cFAPdSo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
